# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="evil-keypad"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Modal command dispatch that speaks native Emacs keybindings"

HOMEPAGE="https://github.com/achyudh/evil-keypad"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/which-key"
RDEPEND="app-emacs/which-key"
