# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="single"
REALNAME="ob-git-permalink"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Easy code citation from repository hosting service"

HOMEPAGE="https://github.com/kijimaD/ob-git-permalink"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
