# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="initsplit"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="[No description available]"

HOMEPAGE="http://www.gci-net.com/users/j/johnw/emacs.html"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
