# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="dired-k"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="highlight dired buffer by file sie, modified time, git status"

HOMEPAGE="https://github.com/syohex/emacs-dired-k"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
