# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="textmate"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="[No description available]"

HOMEPAGE="https://github.com/defunkt/textmate.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
