# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="tar"
REALNAME="copilot-chat"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Copilot chat interface"

HOMEPAGE="https://github.com/chep/copilot-chat.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
