# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="single"
REALNAME="prompt-text"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Various information in minibuffer prompt"

HOMEPAGE="https://github.com/10sr/prompt-text-el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
