# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://stable.melpa.org/packages/"
SOURCE_TYPE="single"
REALNAME="ob-solidity"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="org-babel functions for solidity evaluation"

HOMEPAGE="https://github.com/hrkrshnn/ob-solidity"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
